package openproject;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : DB_Ctrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class DB_Ctrl {
	public void vaildValueCheck() {
	}
	
	public void useTimeSave() {
	}
	
	public void useTimeCall() {
	}
	
	public void seatDataSave() {
	}
	
	public void seatDataDelete() {
	}
	
	public void lockerDataSave() {
	}
	
	public void userInformationSave() {
	}
	
	public void userInformationCall() {
	}
	
	public void seatDataUpdate() {
	}
	
	public void useableLockerDataUpdate() {
	}
}
