package openproject;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.*;

//

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : LoginCtrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//

/**
 * IT독서실 예약 시스템의 로그인 처리를 하는 클래스이다.
 * 입력 받은 ID와 PW의 유효성을 검사한다.
 * @Param id 로그인 아이디
 * @Param pass 로그인 패스워드
 * @Param input_id 입력받은 아이디
 * @Param input_pw 입력받은 패스워드
 * @return: 일치하면 true, 불일치하면 false 리턴
 * @author: 이태희
 * @version: 1.0
 */



public class LoginCtrl {
	private String id;
	private String pass;
	public LoginCtrl() {}
	boolean checkverify(String id, String pass, String input_id, String input_pw) {
		this.id = id;
		this.pass = pass;
			if(id.equals(input_id) &&  pass.equals(input_pw)) {

                return true;
        } 
			else 

				return false; 

	}
		
	
}
