package openproject;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.*;

//

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : LoginCtrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class LoginCtrl {
	private String id;
	private String pass;
	public LoginCtrl() {}
	boolean checkverify(String id, String pass, String input_id, String input_pw) {
		this.id = id;
		this.pass = pass;
			if(id.equals(input_id) &&  pass.equals(input_pw)) {

                return true;
        } 
			else 

				return false; 

	}
		
	
}
