package openproject;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : PurchaseHourPeriod_Ctrl.java
//  @ Date : 2021-12-10
//  @ Author : 홍아현
//
//

/**
 *  IT독서실 예약 시스템의 시간/정기권 구매를 처리한다.
 *  PurchaseHourPeriodScreen에서 사용자가 선택한 버튼의 인덱스 번호를 저장해서 받아온다.
 *  사용자의 구매 전 이용시간에 위에서 받아온 index1를 이용해서 구매한 시간을 더해준다.
 * @author 홍아현
 *
 */
class PurchaseHourPeriod_Ctrl extends PurchaseHourPeriodScreen  {
	
	PurchaseHourPeriodScreen pchp; //구매 화면 객체
	int hour_index = pchp.index; // 구매 화면 인덱스 받아오기
	String hour; //이용 시간
	String price; //이용 금액
	int index=0;
	LoginScreen user;
	String [] customer_id = {"kim", "na", "hyun", "Rewind", "Hong", "ang", "hyun", "lee","tae", "hee", "jang", "yun", "seo"}; // 독서실 이용 고객 명단
	int [] customer_remain_time = {1, 2, 3,45,85,41,12,65,9,10,11,0,13}; // 독서실 이용 고객의 남아있는 이용시간
	int [] inthour = {2, 4,6,8,10,12,24,168,360,720,1440,2160}; //String으로 저장된 시간/기간을 int형 시간으로 변환함
	/**
	 *  시간/정기권 구매화면에서 객체를 생성한다. 
	 */
	public void purchase_Ctrl() {
		pchp = new PurchaseHourPeriodScreen();
		
	}
	
	/**
	 * 사용자가 시간/정기권 구매화면에서 선택한 시간/기간을 불러온다
	 * 이를 위해 구매화면의 객체를 이용한다
	 * 구매한 사용자의 아이디를 알기위해 로그인화면의 객체를 생성하여 이용한다.
	 * 구매한 사용자의 아이디와 독서실 이용 고객의 명단 배열을 비교하여 같다면 index에 배열번호를 저장한다.
	 * 독서실 이용 고객의 남은 이용시간 배열을 이용하여 고객이 구매한 시간을 더해서 업데이트한다.
	 *
	 */
	public void getPurchaseHour() {
		pchp = new PurchaseHourPeriodScreen();
		user = new LoginScreen();
		String user_id = user.id; // 로그인화면에서 사용자 아이디 받아오기
		for(int i=0;i<customer_id.length;i++) { // 로그인한 사용자와 고객 명단 배열 비교
			if(user_id==customer_id[i]) {
				break;
			}
			else if(user_id!=customer_id[i]) index++;
		}
		
		customer_remain_time[index] += inthour[hour_index]; // 시간 업데이트
	}
	
	/**
	 * 사용자가 시간/정기권 구매화면에서 선택한 기간원의 금액을 불러온다
	 * 이를 위해 구매화면의 객체를 이용한다
	 * @return 사용자가 선택한 시간/정기권에 해당하는 금액
	 */
	public String getPurchasePrice() {
		pchp = new PurchaseHourPeriodScreen();
		price = pchp.price;
		return price;
	}
	
	
}
